version: "3.9"

services:
    backend-api:
        build:
            context: ./backend-api
            dockerfile: Dockerfile
        ports:
            - "5000:5000"
        networks:
            - react-flask-net

    backend-websocket:
        build:
            context: ./backend-websocket
            dockerfile: Dockerfile
        ports:
            - "5001:5001"
        networks:
            - react-flask-net

    nginx:
        build:
            context: .
            dockerfile: ./nginx/Dockerfile
        ports:
            - "3000:80"
        depends_on:
            - backend-api
            - backend-websocket
        networks:
            - react-flask-net

networks:
    react-flask-net:
        driver: bridge
